namespace: gitops-todo
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patch-deployment.yaml
configMapGenerator:
- behavior: merge
  literals:
  - POSTGRES_HOST="my-postgres-postgresql"
  - POSTGRES_DB="todo_db"
  - POSTGRES_USER="admin"
  name: postgres-config
